### ISSUE TITLE
Enabling SSL without certs on the build machine.

### ISSUE THREAD

**Issue by lpmartineau** [geerlingguy/php-apache-container#7]
Good Day,
I am using this playbook to create a docker container and I am using the other geerlingguy roles that it pulls in. (-apache, -php for example) and I am struggling with ssl certs. I want to enable SSL in my container but I am using a docker build machine and the certificates are not on this machine. Even if they were I am not sure how to expose them to the playbook so that the apache config file test is successful. 

Thank you.

**Comment by geerlingguy** [comment]
If you would like to run a docker container with SSL certs, there are a few different things you could do:

  1. Copy certs into the container when you build it.
  2. Have an entrypoint or script that runs on container start that copies in the certs before starting Apache.
  3. Mount a volume into the container with the certs inside.

I usually go with the latter option in production environments, but it's not something this particular project would be able to help with, as it's a more generic problem.
